### ISSUE TITLE
[Task] Integrate translation service in DevOps

### ISSUE THREAD

**Issue by JimiC** [vscode-icons/vscode-icons#1194]
We have decided to use a service to better manage the localization of the extension.
The service chosen is [Crowdin](https://crowdin.com).

To integrate the service with our repo a configuration file (`crowdin.yml`) is needed.

The content of the file must be:

```yaml
files:
  - source: package.nls.json
    translation: /package.nls.%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        zh-CN: zh-cn
        zh-TW: zh-tw
  - source: /locale/lang.en.json
    translation: /locale/lang.%two_letters_code%.json
    languages_mapping:
      two_letters_code:
        zh-CN: zh-cn
        zh-TW: zh-tw

```
